# Generated by Django 2.2.26 on 2022-01-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220124_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
